# Application Configuration
spring:
  application:
    name: enrollment-service

  # MySQL Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/enrollment_db
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

# Server Configuration
server:
  port: 8083

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


jwt:
  secret: vFcFcowxQmsBLJ8oX/9ZogEmxERKBnDrlTMyaz4fLLU=