server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=0

        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/api/v1/courses/**
          filters:
            - StripPrefix=0

        - id: enrollment-service
          uri: lb://enrollment-service
          predicates:
            - Path=/api/v1/enrollments/**
          filters:
            - StripPrefix=0

eureka:
  client:
    service-url:
      defaultZone: http://course-server:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
