### Register instructor

POST http://localhost:8081/api/v1/auth/register
Content-Type: application/json

{
  "firstName": "Zainab",
  "lastName": "Lawal",
  "email": "zainab@example.com",
  "password": "teach456",
  "role": "INSTRUCTOR"
}



###
POST http://localhost:8081/api/v1/auth/register
Content-Type: application/json

{
  "firstName": "Chuka",
  "lastName": "Okeke",
  "email": "chuka@example.com",
  "password": "password123",
  "role": "USER"
}

###
POST http://localhost:8081/api/v1/auth/login
Content-Type: application/json

{
  "email": "zainab@example.com",
  "password": "teach456"
}