### Register an Instructor
POST http://localhost:8081/api/v1/auth/register
Content-Type: application/json

{
  "firstName": "Superman",
  "lastName": "Clark",
  "email": "superman@gmail.com",
  "password": "suoerman123",
  "role": "INSTRUCTOR"
}

###

### Login as Instructor
POST http://localhost:8081/api/v1/auth/login
Content-Type: application/json

{
  "email": "superman@gmail.com",
  "password": "suoerman123"
}

###

### Create a Course (as Instructor)
POST http://localhost:8082/api/v1/courses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdXBlcm1hbkBnbWFpbC5jb20iLCJpYXQiOjE3NTI3NTI2NjEsImV4cCI6MTc1MjgzOTA2MX0.rilxrLAQX1lMv5aziCkpNK-RuESrhb0LJXTuYLJWSsk

{
  "title": "Javascript Fundamentals",
  "description": "Learn Javascrpt from scratch",
  "instructorId": 10
}

###

### Get My Courses (as Instructor)
GET http://localhost:8082/api/v1/courses/my-courses
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdXBlcm1hbkBnbWFpbC5jb20iLCJpYXQiOjE3NTI3NTI2NjEsImV4cCI6MTc1MjgzOTA2MX0.rilxrLAQX1lMv5aziCkpNK-RuESrhb0LJXTuYLJWSsk
###

### Approve Course (as Admin)
PUT http://localhost:8082/api/v1/courses/6/approve
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmZW1pZmFsYXNlMjI4QGdtYWlsLmNvbSIsImlhdCI6MTc1Mjc0NDY2MSwiZXhwIjoxNzUyODMxMDYxfQ.svBHB-HMfw2Q2gAdmJgS3Ev_AUcZLX6KjkkSCFt3NaA