### Register instructor

POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "firstName": "Pluto",
  "lastName": "Moon",
  "email": "p@example.com",
  "password": "Eathmoon1234",
  "role": "INSTRUCTOR"
}

###
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "p@example.com",
  "password": "Eathmoon1234"
}
###

### Create a Course (as Instructor)
POST http://localhost:8080/api/v1/courses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiSU5TVFJVQ1RPUiIsInVzZXJJZCI6Mywic3ViIjoicEBleGFtcGxlLmNvbSIsImlhdCI6MTc1MjgwNDAyMiwiZXhwIjoxNzUyODkwNDIyfQ.9m9zlCLY9c9FgtixkjGH2qcaed6VIjg2K2c6MEz26uE

{
  "title": "Pythhon Fundamentals",
  "description": "Learn Ruby from scratch",
  "instructorId": 8
}

###
### Get My Courses (as Instructor)
GET http://localhost:8080/api/v1/courses/my-courses
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdXBlcm1hbkBnbWFpbC5jb20iLCJpYXQiOjE3NTI3NTI2NjEsImV4cCI6MTc1MjgzOTA2MX0.rilxrLAQX1lMv5aziCkpNK-RuESrhb0LJXTuYLJWSsk
###

### Approve Course (as Admin)
PUT http://localhost:8080/api/v1/courses/8/approve
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmZW1pZmFsYXNlMjI4QGdtYWlsLmNvbSIsImlhdCI6MTc1Mjc0NDY2MSwiZXhwIjoxNzUyODMxMDYxfQ.svBHB-HMfw2Q2gAdmJgS3Ev_AUcZLX6KjkkSCFt3NaA

###

### 2. View All Approved Courses (optional, to get a courseId)
GET http://localhost:8080/api/v1/courses
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdXBlcm1hbkBnbWFpbC5jb20iLCJpYXQiOjE3NTI3NTI2NjEsImV4cCI6MTc1MjgzOTA2MX0.rilxrLAQX1lMv5aziCkpNK-RuESrhb0LJXTuYLJWSsk
Accept: application/json

###
### 3. Enroll in a Course (replace <JWT> and <courseId>)
POST http://localhost:8080/api/v1/enrollments
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiVVNFUiIsInVzZXJJZCI6Miwic3ViIjoianVwaXRlckBleGFtcGxlLmNvbSIsImlhdCI6MTc1MjgwMzQ4NiwiZXhwIjoxNzUyODg5ODg2fQ.4rlaa2kLpMImdJEfLv4STnj4vyIyNUGmC0IcFBVvIkI
Content-Type: application/json

{
  "courseId": 9
}

###
### 4. View My Enrollments
GET http://localhost:8080/api/v1/enrollments
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiVVNFUiIsInVzZXJJZCI6Miwic3ViIjoianVwaXRlckBleGFtcGxlLmNvbSIsImlhdCI6MTc1MjgwMzQ4NiwiZXhwIjoxNzUyODg5ODg2fQ.4rlaa2kLpMImdJEfLv4STnj4vyIyNUGmC0IcFBVvIkI
Accept: application/json



