# Application Configuration
spring:
  application:
    name: course-service

  # Database Configuration - Using environment variables
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://mysql:3306/coursedb?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:admin}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:false}  # Turn off for production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

# Server Configuration - CRITICAL CHANGE
server:
  port: ${PORT:8082}  # Must use PORT environment variable

# Eureka Client Configuration
eureka:
  client:
    enabled: ${EUREKA_ENABLED:false}  # ADD this line to disable for cloud
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://course-server:8761/eureka}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

# JWT Configuration - Use environment variable for security
jwt:
  secret: ${JWT_SECRET:vFcFcowxQmsBLJ8oX/9ZogEmxERKBnDrlTMyaz4fLLU=}

# Logging configuration
logging:
  level:
    com.yourpackage: ${LOG_LEVEL:INFO}
    org.springframework.web: WARN
    org.hibernate.SQL: ${SQL_LOG_LEVEL:WARN}