# Application Configuration
spring:
  application:
    name: course-service

  # MySQL Database Configuration
  datasource:
    url: jdbc:mysql://mysql:3306/coursedb?createDatabaseIfNotExist=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

# Server Configuration
server:
  port: 8082

# Eureka Client Configuration
eureka:
  client:
    register-with-eureka: true       # ✅ Register with Eureka
    fetch-registry: true             # ✅ Fetch service regist
    service-url:
      defaultZone: http://course-server:8761/eureka
  instance:
    prefer-ip-address: true

jwt:
  secret: vFcFcowxQmsBLJ8oX/9ZogEmxERKBnDrlTMyaz4fLLU=