# Application Configuration
spring:
  application:
    name: user-service
  
  # MySQL Database Configuration
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://mysql:3306/userdb?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:admin}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

# Server Configuration
server:
  port: ${PORT:8081}

# Eureka Client Configuration
eureka:
  client:
    register-with-eureka: ${EUREKA_ENABLED:false}       # ✅ Register with Eureka
    fetch-registry: true             # ✅ Fetch service regist
    service-url:
      defaultZone: ${EUREKA_URL:http://course-server:8761/eureka}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}


jwt:
  secret: ${JWT_SECRET:vFcFcowxQmsBLJ8oX/9ZogEmxERKBnDrlTMyaz4fLLU=}


# Logging configuration
logging:
  level:
    com.yourpackage: ${LOG_LEVEL:INFO}
    org.springframework.web: WARN
    org.hibernate.SQL: ${SQL_LOG_LEVEL:WARN}